# This workflow will test citrix-adc-frrouting-sync as a daemon

name: Daemon integration testing

on: [push, pull_request]

jobs:
  daemon_integration_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip3 install pytest pytest-ordering
        if [ -f requirements.txt ]; then sudo pip3 install -r requirements.txt; fi
    - name: Install frrouting
      run: |
        curl -s https://deb.frrouting.org/frr/keys.asc | sudo apt-key add
        FRRVER="frr-stable"
        echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | sudo tee -a /etc/apt/sources.list.d/frr.list -
        sudo apt update && sudo apt install frr frr-pythontools
    - name: Start citrx-adc-frrouting-sync as a deamon before starting frrouting and citrix ADC to check survivability
      run: |
        sudo ./run.py --config sample-config/config.ini -d
    - name: Start frrouting
      run: |
        sudo service frr start
    - name: Configure integration testing environment and start Citrix ADC CPX
      run: |
        echo ${{ secrets.dockerhub_password }} | docker login -u ${{ secrets.dockerhub_login }} --password-stdin
        docker-compose -f docker-compose.ci.yml up -d
        docker ps
        echo 'Waiting for Citrix ADC CPX initialization (90s)'
        sleep 90
        echo 'Testing NITRO API access'
        curl -sS -H "X-NITRO-USER:nsroot" -H "X-NITRO-PASS:nsroot" http://localhost:9080/nitro/v1/config/server
    - name: Integration testing with Citrix ADC CPX 13
      run: |
        sudo python3 -m pytest tests/integration/

