# This workflow will test citrix-adc-frrouting-sync as a daemon

name: Daemon integration testing

on: [push, pull_request]

jobs:
  daemon_integration_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        curl -s https://deb.frrouting.org/frr/keys.asc | sudo apt-key add
        FRRVER="frr-stable"
        echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | sudo tee -a /etc/apt/sources.list.d/frr.list -
        sudo apt update && sudo apt install frr frr-pythontools python3-pip
        sudo pip3 install python-daemon==2.2.4
    - name: Start citrx-adc-frrouting-sync as a deamon before starting frrouting and citrix ADC to check survivability
      run: |
        sudo ./run.py --config sample-config/config.ini -d
    - name: Start frrouting
      run: |
        sudo service frr start
    - name: Configure integration testing environment and start Citrix ADC CPX
      run: |
        echo ${{ secrets.dockerhub_password }} | docker login -u ${{ secrets.dockerhub_login }} --password-stdin
        docker-compose -f docker-compose.ci.yml up -d
        docker ps
        echo 'Waiting for Citrix ADC CPX initialization (90s)'
        sleep 90
        echo 'Testing NITRO API access'
        curl -sS -H "X-NITRO-USER:nsroot" -H "X-NITRO-PASS:nsroot" http://localhost:9080/nitro/v1/config/server
    - name: Integration testing with Citrix ADC CPX 13
      run: |
        echo "########### Create new LB vserver and test route injection when LB vserver is up ###########"
        echo 'Injecting initial config'
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'add ns ip 10.1.2.3 255.255.255.255 -type VIP -hostroute ENABLED'
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'enable ns feature LoadBalancing'
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'add service google_ssl_svc 216.58.206.227 SSL 443'
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'add lb vserver google_http_vsrv HTTP 10.1.2.3 80'
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'bind lb vserver google_http_vsrv google_ssl_svc'
        wait(10)
        sudo vtysh -c 'show ip route tag 99'
        echo "########### Disable service to down LB vserver to test rute withdrawal ###########"
        docker exec -i citrix-adc-frrouting-sync_cpx_130_1 cli_script.sh 'disable service google_ssl_svc'
        wait(10)
        sudo vtysh -c 'show ip route tag 99'

